### PR TITLE
Traitlets fix

### LINKED ISSUE #602: CDS Dashboard seems to be broken
This happens on aws deployment from the latest main branch with password user.

<img width="812" alt="Screenshot 2021-05-24 at 21 53 27" src="https://user-images.githubusercontent.com/5647941/119377205-7b275600-bcda-11eb-936e-c3c71ac34273.png">

K8s hub logs:
```python
 [I 2021-05-24 16:20:56.769 JupyterHub log:189] 200 GET /hub/api/users (cull-idle@127.0.0.1) 8.52ms                                                                                                           │
│ [E 2021-05-24 16:21:53.587 JupyterHub pages:262] Failed to spawn single-user server with form                                                                                                                │
│     Traceback (most recent call last):                                                                                                                                                                       │
│       File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/pages.py", line 255, in post                                                                                                          │
│         options = await maybe_future(spawner.options_from_form(form_options))                                                                                                                                │
│       File "/opt/conda/lib/python3.7/site-packages/cdsdashboards/hubextension/spawners/variablemixin.py", line 333, in options_from_form                                                                     │
│         formdata = super().options_from_form(options)                                                                                                                                                        │
│       File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 575, in __get__                                                                                                             │
│         return self.get(obj, cls)                                                                                                                                                                            │
│       File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 538, in get                                                                                                                 │
│         default = obj.trait_defaults(self.name)                                                                                                                                                              │
│       File "/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py", line 1575, in trait_defaults                                                                                                     │
│         "instances" % (n, type(self).__name__))                                                                                                                                                              │
│     traitlets.traitlets.TraitError: 'options_from_form' is not a trait of 'VariableKubeSpawner' instances                                                                                                    │
│                                                                                                                                                                                                              │
│ [I 2021-05-24 16:21:53.592 JupyterHub log:189] 200 POST /hub/spawn/example-user (example-user@10.10.1.245) 11.18ms                                                                                           │
│ [I 2021-05-24 16:21:56.677 JupyterHub proxy:347] Checking routes
```

cc @danlester

### PR DESCRIPTION
**Pull request by danlester**
Traitlets >= 5.0 seems to have a backwards-incompatibility that affected the VariableSpawner used in cdsdashboards.

This works around it.

Closes #602

### CODE REVIEW

**Comment by danlester** [comment]
This needs cdsdashboards 0.5.7 which is now available on conda-forge, but doesn't seem to be picked up in the GitHub Actions docker build yet... maybe wait to see if these can be re-run tomorrow.

**Comment by aktech** [comment]
Seems like there is an issue with JupyterHub docker image build.

**Comment by danlester** [comment]
Yes, I think it needs to wait for some conda-forge cache to clear or something (as noted above). Will try it again tomorrow.

**Comment by danlester** [comment]
@aktech Have rerun and it's much happier now - it just needed a good sleep.

**Comment by aktech** [comment]
Awesome, thanks @danlester

**Review by aktech — APPROVED** [review]

**Pull request merged**
