### PR TITLE
feat: add r-studio to jupyterlab image

### LINKED ISSUE #896: [enhancement] Add R-Studio and xfce (desktop enviroment) profiles
## Description

Currently users are able to launch Jupyterlab instances (Ubuntu only, with CentOS to come). From my discussion with @costrouc, it would be great to have the ability to launch R-Studio and even a desktop environment like [xfce](https://www.xfce.org/). 

## Value/benefit

This would enhance the the user-experience and potentially attract a large pool of users.

### PR DESCRIPTION
**Pull request by HarshCasper**
Fixes #896 

## Changes introduced in this PR:

- Add R-Studio

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [X] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [X] No

## Additional comments

With this, both [RStudio](https://www.rstudio.com/) and [IRKernel](https://irkernel.github.io/) are installed by default, so the user can use either the Jupyter interface or the RStudio interface.

For some R packages, there is no corresponding conda-forge package yet, in that case, take a look at https://github.com/binder-examples/r. Note that these two approaches cannot be combined, so we cannot install R packages via Conda and via an `install.R` file at the same time.

### CODE REVIEW

**Review by iameskild — COMMENTED** [review]
@HarshCasper is there a specific need to add these packages now?

I don't necessarily see an issue besides a slightly larger image. On a related note. Chris and others have expressed an interest in image clean up, https://github.com/Quansight/qhub/issues/1145. That and given that we are [transferring the images](https://github.com/nebari-dev/nebari-docker-images/pull/1) into its own repo, makes we think we should hold off with this for now.
What are your thoughts?

Maybe we can spend some time after these sprints to work on the image clean up together 👍

**Comment by dharhas** [comment]
Why is this being worked on right now. RStudio has a slightly funky license that we need to evaluate first.

**Comment by magsol** [comment]
> @HarshCasper is there a specific need to add these packages now?
> Maybe we can spend some time after these springs to work on the image clean up together 👍

Agreed, this needs more discussion (including but not limited to licensing) and isn't a priority right now, so let's hold for awhile.

**Comment by iameskild** [comment]
@HarshCasper I'm going to close this for now. We can circle back to image clean up at a later time 👍

**Pull request closed without merging**
