### PR TITLE
Add docs for deploying QHub to existing EKS cluster

### LINKED ISSUE #942: [documentation] Document deployment on existing AWS EKS cluster
Related to #935. 

To test and document how to deploy to an existing ("local") EKS cluster, I ran through the following steps:

## Use (create) base EKS cluster

To get a functioning EKS cluster up and running quickly, I created a cluster and web app based on this [tutorial](https://logz.io/blog/amazon-eks-cluster/). This cluster is running in it's own VPC with 3 subnets (each in it's own AZ) and there are no node groups. A scenario like seemed like a good place to start from the perspective of an incoming user.

Once this EKS cluster is up, there are still a handful of steps that seem to be required before QHub can be deployed to it:
- Ensure that the subnets are allowed to "automatically assign public IP addresses to instances launched into it" otherwise node group can't be launched
- Create `general`, `user` and `worker` node groups
  - Attach `Node IAM Role` with specific permissions (copied from existing role from previous qhub deployment):
  - Configure node group being mindful of instance size, attached block storage size and auto-scaling features. 

I'm sure there are scenarios where there already exists node groups and they can be repurposed but more broadly it would be nice to make this process a lot more streamlined. Did I overcomplicate this, or are there other ways of handling the QHub deployment without having to add these node groups explicitly? 

## Deploy QHub to Existing EKS Cluster

Ensure that you are using the existing cluster's `kubectl` context. 

Initialize in the usual manner:
```
python -m qhub init aws --project eaeexisting --domain eaeexisting.qhub.dev --ci-provider github-actions --auth-provider github --auth-auto-provision --repository github.com/iameskild/eaeaws
```

Then update the `qhub-config.yaml` file. The important keys to update are:
- Replace `provider: aws` with `provider: local`
- Replace `amazon_web_services` with `local`
  - And update the `node_selector` and `kube_context` appropriately

Once updated, deploy in the usual manner:

```
python -m qhub deploy --config qhub-config.yaml --disable-prompt --dns-provider cloudflare --dns-auto-provision
```

The deployment completes successfully and all the pods appear to be running (alongside the existing pods from the web app). The issue is that I can't access the cluster from the browser:

```
404 page not found
```

When examining the print statement from the deployment more, you can see that the cluster doesn't have an IP address:

```
[terraform]: ingress_jupyter = {
[terraform]:   "hostname" = "aea1abf087211438cbf9e44ef5fb64c3-197330438.us-east-2.elb.amazonaws.com"
[terraform]:   "ip" = ""
[terraform]:
```

###  `qhub-config.yaml` 
<details>

```
project_name: eaeexisting
provider: local
domain: eaeexisting.qhub.dev
certificate:
  type: self-signed
security:
  authentication:
    type: GitHub
    config:
      client_id: 
      client_secret:
      oauth_callback_url: https://eaeexisting.qhub.dev/hub/oauth_callback
  users:
    iameskild:
      uid: 1000
      primary_group: admin
      secondary_groups:
      - users
  groups:
    users:
      gid: 100
    admin:
      gid: 101
default_images:
  jupyterhub: quansight/qhub-jupyterhub:v0.3.13
  jupyterlab: quansight/qhub-jupyterlab:v0.3.13
  dask_worker: quansight/qhub-dask-worker:v0.3.13
  dask_gateway: quansight/qhub-dask-gateway:v0.3.13
  conda_store: quansight/qhub-conda-store:v0.3.13
storage:
  conda_store: 60Gi
  shared_filesystem: 100Gi
theme:
  jupyterhub:
    hub_title: QHub - eaeexisting
    hub_subtitle: Autoscaling Compute Environment on Amazon Web Services
    welcome: Welcome to eaeexisting.qhub.dev. It is maintained by <a href="http://quansight.com">Quansight
      staff</a>. The hub's configuration is stored in a github repository based on
      <a href="https://github.com/Quansight/qhub/">https://github.com/Quansight/qhub/</a>.
      To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub/issues">github
      issue tracker</a>.
    logo: /hub/custom/images/jupyter_qhub_logo.svg
    primary_color: '#4f4173'
    secondary_color: '#957da6'
    accent_color: '#32C574'
    text_color: '#111111'
    h1_color: '#652e8e'
    h2_color: '#652e8e'
monitoring:
  enabled: true
cdsdashboards:
  enabled: true
  cds_hide_user_named_servers: true
  cds_hide_user_dashboard_servers: false
ci_cd:
  type: github-actions
  branch: main
terraform_state:
  type: remote
namespace: dev
local:
  kube_context: arn:aws:eks:us-east-2:892486800165:cluster/eaeeks
  node_selectors:
    general:
      key: eks.amazonaws.com/nodegroup
      value: general
    user:
      key: eks.amazonaws.com/nodegroup
      value: user
    worker:
      key: eks.amazonaws.com/nodegroup
      value: worker
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 4 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 0.75
      mem_limit: 4G
      mem_guarantee: 2.5G
      image: quansight/qhub-jupyterlab:v0.3.13
  - display_name: Medium Instance
    description: Stable environment with 2 cpu / 8 GB ram
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 1.5
      mem_limit: 8G
      mem_guarantee: 5G
      image: quansight/qhub-jupyterlab:v0.3.13
  dask_worker:
    Small Worker:
      worker_cores_limit: 1
      worker_cores: 0.75
      worker_memory_limit: 4G
      worker_memory: 2.5G
      worker_threads: 1
      image: quansight/qhub-dask-worker:v0.3.13
    Medium Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 8G
      worker_memory: 5G
      worker_threads: 2
      image: quansight/qhub-dask-worker:v0.3.13
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - qhub-dask ==0.3.13
    - python-graphviz
    - numpy
    - numba
    - pandas
  environment-dashboard.yaml:
    name: dashboard
    channels:
    - conda-forge
    dependencies:
    - python==3.9.7
    - ipykernel==6.4.1
    - ipywidgets==7.6.5
    - qhub-dask==0.3.13
    - param==1.11.1
    - python-graphviz==0.17
    - matplotlib==3.4.3
    - panel==0.12.4
    - voila==0.2.16
    - streamlit==1.0.0
    - dash==2.0.0
    - cdsdashboards-singleuser==0.5.7

```

</details>

### PR DESCRIPTION
**Pull request by iameskild**
Fixes | Closes | Resolves #942 

> Please remove anything marked as optional that you don't need to fill in. Choose one of the keywords preceding to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:

Add documentation on how to deploy QHub to an existing EKS cluster. 

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [ ] Yes
- [x] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [x] No

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and more.

### CODE REVIEW

**Comment by phobson** [comment]
Hey folks,

I've reviewed the new docs and they clarify a few things, but I'm personally still having trouble deploying to my org's existing server. A few things to keep in mind is that 1) I'm not great with the web and 2) really just getting started with distributed computing. I realize the Qhub docs can't explain everything, so if answering any (or all) of the questions below are outside of the scope of Qhub's docs, I would completely understand. 

That said, I'm left unsure about the following things:
1. When I'm configuring and deploying Qhub, should I be would working on my local machine (laptop) or should I be working in a terminal attached to the cluster? This question mainly comes from confusion around the "aws" vs "local" value of the provider? What is "local" here?
2. Cloudflare's role is unclear to me. This is largely because my org and I aren't necessarily looking for a Jupyter Hub interface. We just want to be able to use a YML file to provision/configure our workers in the cluster
3. Beyond the Qhub config file, what is required to be in the Github repository? I suppose the github actions need to be configured as well, but do we have to have a webservice in the repo as well?

Again, I'm basically starting from scratch here, so please take the questions mostly as things I'm asking myself to figure out and not as burden on the Qhub team.

**Comment by iameskild** [comment]
Hey @phobson, thanks for the reaching out. I'll see if I can answer some of these questions:

1. The term `local` is a bit misleading but refers to an "existing" kubernetes cluster (labeled `local` for historical reasons, updating this label might be worthwhile in the future). So long as you have set the appropriate [`kubectl`](https://kubernetes.io/docs/reference/kubectl/cheatsheet/) context when working with your AWS kubernetes (EKS) cluster and `qhub`, you should be fine to interact with the cluster from your laptop. This does require that you have `kubectl` installed. If you have an existing AWS kubernetes cluster you would like to deploy QHub to, then `local` is what you want.
2. Cloudflare is a DNS service, creating a record so that your qhub domain can be resolved. QHub deploys a Jupyterhub (with many additional features such as dask integration, dash-boarding and more) so I'm not entirely sure what you mean by use the `YML to configure/provision our workers`. This YML is used to provision users so they can login to a JupyterLab session (authenticated and connected to JupyterHub). Be warned that QHub is moving away from provisioning users in this `qhub-config.yaml` and replacing it with keycloak. 
3. The github repo for your deployment is not necessary, but a recommended way of tracking changes to your QHub "infrastructure". An admin can make changes to the `qhub-config.yaml`, merge those changes into the repo and whereby those changes will automatically be deployed. 
4. If you're deploying from `main` (ie a "dev" install), then you will be picking up the switch to keycloak (not yet released). I would recommend deploying from a stable version, 0.3.13 (or 0.3.14, just released).

I hope that sheds a little light on some of these questions. We are definitely interested in ways we can improve our documentation, so if there are specific areas that are unclear or misleading, feel free to let me know or open an issue. Thanks again :)

**Comment by phobson** [comment]
Thanks @iameskild. One last thing that I meant to ask above, but omitted is this: How externally exposed does the cluster need to be for the Cloudfare registration to work? My guess is that properly configuring the `kubectl` context handles this. But, again, I'm pretty green here. 

Thanks for the note about sticking to releases and the incoming `keycloak` change.

**Review by tylerpotts — APPROVED** [review]
LGTM

**Comment by tylerpotts** [comment]
@phobson Configuring the kubectl context is more about authenticating so you can interact with the kubernetes cluster via the CLI.

The only ip that needs to be exposed is the `qhub-traefik-ingress` service, which is the only cluster resource to have an external IP address. This service acts as a proxy for all requests to the cluster.

I'm going to merge this PR which will close it, but that's certainly no indication that you can't ask further questions. If you have any other comments please feel free to open an issue

**Pull request merged**
