### PR TITLE
Adding tests for juypterhub-ssh, jhub-client, and vs code 

### PR DESCRIPTION
**Pull request by costrouc**
From my testing jupyterhub-ssh does not fully work as an expected ssh session. Currently it is hanging at times with 

```
/opt/conda/condabin/conda
/opt/conda/condabin/conda
```

And then hanging and not giving a shell.

### CODE REVIEW

**Comment by costrouc** [comment]
From my testing jupyterhub-ssh does not fully work as an expected ssh session. Currently it is hanging at times with 

```
/opt/conda/condabin/conda
/opt/conda/condabin/conda
```

And then hanging and not giving a shell.

**Review by danlester — APPROVED** [review]

**Comment by costrouc** [comment]
@danlester I agree. This would make the tests faster. But I don't know how we can get around this since in the UI tests we want to test the `start` and `stop` button. So this will require that at a minimum we start and stop twice.

**Comment by danlester** [comment]
Yes, this was one reason I built the Python tests into Cypress initially - click to Start, then run the tests, then stop!

But as long as multiple notebooks can be done in one session, maybe that's OK.

**Comment by costrouc** [comment]
The `pytest` `test_deployments` will also need to launch servers but this was added with this PR recently

**Pull request merged**
