### PR TITLE
Removing custom dask_gateway from qhub and idle_timeout for dask clusters to 30 min

### LINKED ISSUE #1012: [bug] Unable to connect to dashboard using Dask-Gateway and Labextension
## Describe the bug
Running the following on qhub `v0.3.13` and `v0.3.14` generates an accessible link for the dask cluster dashboards, but we are unable to reuse that link to access the dask extension.

```
from dask_gateway import Gateway
gateway = Gateway()

options = gateway.cluster_options()
options

cluster = gateway.new_cluster(options)
cluster
``` 
successful generates a working URL for the dashboards (can be accessed):
image

Dashboard URL does not work:
image

## Expected behavior

- The Dask lab extension should connect to the dask-gateway spawned cluster

## How to reproduce

- Launch a dask-gateway cluster and include the generated Dashboard URI in the Dask extension bar

### PR DESCRIPTION
**Pull request by costrouc**
This PR removed our custom dask-gateway image from the configuration.

### CODE REVIEW

**Comment by viniciusdc** [comment]
So, just to be sure. We will not support custom dask-gateway images then?

**Comment by costrouc** [comment]
@viniciusdc correct. The only reason that we used a custom version was due to needing a tls option to be set.

**Comment by viniciusdc** [comment]
@costrouc when you have some time, could you check the conflicts here? We tested this already right?

**Comment by costrouc** [comment]
Yeah @viniciusdc I will rebase and re-run the tests.

**Comment by costrouc** [comment]
Ready for review

**Review by viniciusdc — APPROVED** [review]
LGTM! I tested it with a local deployment and with GCP. I was able to notice that the idle_timeout worked and killed the gateway cluster.  No other issues with TLS as well, used lets-encrypt to test

**Comment by viniciusdc** [comment]
@costrouc before merging this, could you remove the docker build step from the docker CI test?

**Comment by costrouc** [comment]
Thanks for testing this @viniciusdc. Yes this will not fix the auth issues with jupyterlab extensions.

**Pull request merged**
