### PR TITLE
Generate independet objects for terraform-state resources

### LINKED ISSUE #1082: [bug] Qhub Azure deploy fails when remote state is activated
## Describe the bug

According to some recent intagration tests logs, it seems that qhub is trying to create two resource groups with the same name, resulting in the error below:
```
[terraform]: azurerm_resource_group.resource_group: Creating...
[terraform]: ╷
[terraform]: │ Error: A resource with the ID "/subscriptions/***/resourceGroups/<rg-name>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_resource_group" for more information.
[terraform]: │ 
[terraform]: │   with azurerm_resource_group.resource_group,
[terraform]: │   on main.tf line 1, in resource "azurerm_resource_group" "resource_group":
[terraform]: │    1: resource "azurerm_resource_group" "resource_group" {
[terraform]: │ 
[terraform]: ╵
```
the error seems to be caused by the presence of another resource group created during `01-terraform-state` stage:
```
INFO:qhub.provider.terraform:terraform apply directory=stages/01-terraform-state/azure targets=[]
INFO:qhub.provider.terraform: terraform at /tmp/terraform/1.0.5/terraform
[terraform]: 
[terraform]: Terraform used the selected providers to generate the following execution
[terraform]: plan. Resource actions are indicated with the following symbols:
[terraform]:   + create
[terraform]: 
[terraform]: Terraform will perform the following actions:
[terraform]: 
[terraform]:   # module.terraform-state.azurerm_resource_group.terraform-resource-group will be created
[terraform]:   + resource "azurerm_resource_group" "terraform-resource-group" {
[terraform]:       + id       = (known after apply)
[terraform]:       + location = "eastus"
[terraform]:       + name     = "<rg-name>"
[terraform]:     }
...
[terraform]: module.terraform-state.azurerm_resource_group.terraform-resource-group: Creating...
[terraform]: module.terraform-state.azurerm_resource_group.terraform-resource-group: Creation complete after 1s [id=/subscriptions/***/resourceGroups/<rg-name>]
```

The possible solution here would be 
- removing the resource group creation (and any possible duplicate resource) from the `01` stage -- this might not be feasible depending on the reason it was in there
- Using the new python dynamic system to overwrite the `02` stage to import the necessary resources to state using `data`

## Expected behaviour

- A successeful deployment of an Azure qhub cluster

## How to reproduce

- deploy qhub from main and initialize an Azure deployment with `terraform-state=remote`

### PR DESCRIPTION
**Pull request by viniciusdc**
Fixes | Closes | Resolves #1082 

This PR should fix the above-linked issue by creating specific groups, containers, and storage resources for terraform-state files.

## Changes introduced in this PR:

- Update resource group name, for terraform state stage
- Update backend configuration following the same changes
- Add a new variable to deploy for the custom resource group name (in theory)

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [ ] Yes
- [x] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by costrouc — CHANGES_REQUESTED** [review]
@viniciusdc this looks good to me. Can you verify that you can redeploy (without doing destroy in between) and delete the `stages` directory. I want to check that the terraform import is working as expected.

**Comment by viniciusdc** [comment]
Hi @costrouc, testing results:
- Just simple redeploying worked fine, even updating the qhub-config lead to no issue
- Deleting the `stages/` dir and redeplogin lead to the folowing error: 
```
[terraform]: │ Error: A resource with the ID "/subscriptions/********/resourceGroups/qhubstages-dev-state" already exists - to be 
[terraform]: | managed via Terraform this resource needs to be imported into the State. Please see the resource documentation
[terraform]: | for "azurerm_resource_group" for more information.
[terraform]: │ 
[terraform]: │   with module.terraform-state.azurerm_resource_group.terraform-state-resource-group,
[terraform]: │   on modules/terraform-state/main.tf line 1, in resource "azurerm_resource_group" "terraform-state-resource-group":
[terraform]: │    1: resource "azurerm_resource_group" "terraform-state-resource-group" {
[terraform]: │ 
[terraform]: ╵
```

**Comment by viniciusdc** [comment]
Ok, so I forgot to add the correct resource names for the state blocks, so the generated import-config didn't match what was previously submitted.

**Review by costrouc — APPROVED** [review]
Awesome thanks for this quick worker @viniciusdc :smile:

**Pull request merged**
