### PR TITLE
Bump jupyterhub version to 2.2.2

### LINKED ISSUE #1201: [BUG] - kubespawner_overrides end up influencing future profile launches
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

Clicking on any profile within kubespawner should not influence other launches.

### Actual behavior

See above.

### How to Reproduce the problem?

See above.

### Command output

_No response_

### Versions and dependencies used.

_No response_

### Compute environment

_No response_

### Integrations

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by viniciusdc**
Fixes | Closes | Resolves #1201 

## Changes introduced in this PR:

- Bump Jupyterhub version to 2.2.2 

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [x] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danlester** [comment]
Yes, I haven't tried this out yet but I think it is unlikely that dashboards will be accessible to anyone other than the author.

Others have reported problems, due to new RBAC permissions in JupyterHub 2.0+: https://github.com/ideonate/cdsdashboards/issues/96 - I haven't seen a simple solution presented though. It would need some understanding of how the new RBAC works.

**Comment by danlester** [comment]
@viniciusdc Did you reach any conclusion on dashboard sharing? I can (and will) try it out for myself but also want to avoid being the only person who touches anything to do with dashboards!

**Comment by viniciusdc** [comment]
> 

Hi Dan, sorry couldn't check that yet.

**Comment by viniciusdc** [comment]
> @viniciusdc Did you reach any conclusion on dashboard sharing? I can (and will) try it out for myself but also want to avoid being the only person who touches anything to do with dashboards!

Hi Dan, sorry couldn't check that yet. If you have some extra time to show me a little about the dashboards configuration, I can help you too :smile:

**Comment by costrouc** [comment]
This issue / PR is blocked until CDSDashboards properly supports jupyterhub 2.x

**Comment by viniciusdc** [comment]
c.c. @costrouc closing this in reason of #1292, as we are moving some configuration for cdsdashboards permission system.

**Pull request closed without merging**
