### PR TITLE
qhub cli tool to save kubernetes logs - `qhub support`

### PR DESCRIPTION
**Pull request by tarundmsharma**

### CODE REVIEW

**Comment by costrouc** [comment]
@tarundmsharma  could you make the black tests pass?

**Comment by tarundmsharma** [comment]
@costrouc Please help me with review and merge.
Thank you

**Comment by tylerpotts** [comment]
@tarundmsharma It looks like this is failing because of the recently added Prometheus pod. Also please add some documentation on how to use this.

@costrouc Perhaps we have an explicit list of pods that we check against? Either that or we need a test to ensure that the support tool isn't broken when a new pod is added to the cluster.

This is what I ran and the result after running this on a locally deployed QHub based on the latest commit in this branch:
```
$ qhub support -c qhub-config.yaml -o ./qhub-support.zip
Traceback (most recent call last):
  File "/home/tyler/miniconda3/envs/d_support/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/qhub/cli/__init__.py", line 44, in cli
    args.func(args)
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/qhub/cli/support.py", line 51, in handle_support
    raise e
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/qhub/cli/support.py", line 37, in handle_support
    v1.read_namespaced_pod_log(
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 22929, in read_namespaced_pod_log
    return self.read_namespaced_pod_log_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 23048, in read_namespaced_pod_log_with_http_info
    return self.api_client.call_api(
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/home/tyler/miniconda3/envs/d_support/lib/python3.10/site-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 11 Oct 2021 18:34:10 GMT', 'Content-Length': '254'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod alertmanager-kube-prometheus-stack-alertmanager-0, choose one of: [alertmanager config-reloader]","reason":"BadRequest","code":400}

```

**Comment by iameskild** [comment]
I am also getting the issue @tylerpotts mentioned above. Given how potentially useful this `support` command might be when troubleshooting, I will try to get it in a working state.

**Comment by iameskild** [comment]
@tylerpotts @aktech @costrouc with some minor changes, I was able to get this to work. Multi-container pods seemed to be causing the issue lol

**Review by tylerpotts — APPROVED** [review]
LGTM

**Comment by iameskild** [comment]
closes #771

**Pull request merged**
