### PR TITLE
pinning the qhub-dask in qhub-cloud

### LINKED ISSUE #86: Use conda metapackages for environment consistency
We have been facing the problems described at [this medium article](https://medium.com/pangeo/managing-environments-5604d848367a) regarding Management of Virtual Environments.

We already have this problem and are enforcing it manually when creating new conda envs. This is typically the primary reason dask etc fails on new environments etc. The metapackage approach is the only real solution at this point and will also allow us to build a good linter (#119) that can check pull requests.

## Further discussion
There is probably a discussion in terms of whether the conda-store story changes the way we do this. What is the best way to integrate it with conda-store?

### PR DESCRIPTION
**Pull request by viniciusdc**
The metapackage approach for `qhub-dask` allow us to update our pinned versions for dask dependencies. fix #86

### CODE REVIEW

**Comment by costrouc** [comment]
Will need to try and install this environment locally. I'll review it on monday

**Comment by tylerpotts** [comment]
Could we also have bokeh pinned to version 2.2.3 with this? Until we upgrade dask gateway bokeh 2.3 breaks dask clusters

**Comment by costrouc** [comment]
@viniciusdc this PR looks empty was that intentional?

**Comment by viniciusdc** [comment]
> @viniciusdc this PR looks empty was that intentional?

Yup, I am waiting for v0.3 to pin the dependencies with qhub-dask (+bokeh)

**Comment by costrouc** [comment]
Gotcha so this issue in on hold until we create a release?

**Comment by viniciusdc** [comment]
Was this intentional? @costrouc @tylerpotts 
https://github.com/Quansight/qhub-cloud/blob/e66ce2e3d693772583cd804de5ff505829bece1b/tests/assets/config_gcp_gpu.yaml#L132

**Comment by viniciusdc** [comment]
The current pinned versions for `qhub-dask`:
`requirements:
  run:
    - dask ==2.30.0
    - distributed ==2.30.1
    - dask-gateway ==0.9.0
`

**Comment by viniciusdc** [comment]
I think this is right to go, don't?

**Comment by aktech** [comment]
> @aktech Could you have a look at this? The current pin for distributed is 2.30.1 and I don't know if the above environment is correct.

Feel free to change it to `2.30.1` or just use the meta package when it's available. That file is anyways in the tests, so won't really affect anything.

**Comment by viniciusdc** [comment]
> > @aktech Could you have a look at this? The current pin for distributed is 2.30.1 and I don't know if the above environment is correct.
> 
> Feel free to change it to `2.30.1` or just use the meta package when it's available. That file is anyways in the tests, so won't really affect anything.

Thanks, I thought that too, but I was not sure about changing that.

**Comment by viniciusdc** [comment]
@dharhas @costrouc what do you think? is this something we can use for this release?

**Pull request closed without merging**
