### PR TITLE
Fix project name and domain at None

### PR DESCRIPTION
**Pull request by pierrotsmnrd**
## Description

I ran `qhub init aws` and entered my project name, and domain, etc.  And then deployed, and it worked.

Though, when I reach my qhub, the project and domain are both "None" :
Capture d’écran 2021-10-14 à 08 14 10

## Diagnostic

I identified that my `qhub-config.yaml` file contained `None` values, so the problem had to be in the command `qhub init aws`. 

In `initialize.py`, I identified two vars, `project_name` and `qhub_domain`, that were used before the user is prompted to set them up.

## Fix
This is quite straightforward : I simply moved the code using vars `project_name` and `qhub_domain`  _after_ they're set.

### CODE REVIEW

**Comment by aktech** [comment]
@pierrotsmnrd Can you please rebase or merge master so that K8s tests passes?

**Comment by pierrotsmnrd** [comment]
@aktech  merging the main didn't seem to solve the K8s test 🥲

**Comment by viniciusdc** [comment]
Hi, @pierrotsmnrd can you merge main again if possible? Our recent changes to the tests might be the issue here, overall your PR looks good to me, thanks for the contribution :smile:

**Comment by danlester** [comment]
Updating to latest main so we can see if tests re-run OK, then we can merge.

**Comment by iameskild** [comment]
The `Test QHub Provider` workflow is failing because this PR is coming from the @pierrotsmnrd forked repo. This means that the github secrets needed for this test will not be accessible, checkout the [blank `env`s in the workflow](https://github.com/Quansight/qhub/runs/6282487280?check_suite_focus=true#step:6:7). When printing out secrets in GH actions, they are usually in the form `***`.

All that said, given that this change is minor, I'm fine with merging it. What do you think @costrouc @viniciusdc?

**Comment by viniciusdc** [comment]
> The `Test QHub Provider` workflow is failing because this PR is coming from the @pierrotsmnrd forked repo. This means that the github secrets needed for this test will not be accessible, checkout the [blank `env`s in the workflow](https://github.com/Quansight/qhub/runs/6282487280?check_suite_focus=true#step:6:7). When printing out secrets in GH actions, they are usually in the form `***`.
> 
> All that said, given that this change is minor, I'm fine with merging it. What do you think @costrouc @viniciusdc?

I'm fine as well. :+1:

**Pull request merged**
