### PR TITLE
DOCS: QHub 101

### LINKED ISSUE #301: [documentation] - 101 Qhub
## Idea
As we are working on our docs it would be good to have a 101 on QHub Cloud. For inspiration check out the [SpaCy 101](https://spacy.io/usage/spacy-101).
## Action
Have a dedicated webpage to QHub Cloud 101 on the docs heading.

### PR DESCRIPTION
**Pull request by HarshCasper**
Fixes #301

### CODE REVIEW

**Comment by magsol** [comment]
This seems like a good start but I'm not convinced this "fixes" #301, especially given the spaCy example that Tania posted. I think we need to fill out the skeleton with some content before we merge.

**Comment by HarshCasper** [comment]
> This seems like a good start but I'm not convinced this "fixes" #301, especially given the spaCy example that Tania posted. I think we need to fill out the skeleton with some content before we merge.

Hi @magsol 

I am currently working on this. I just added the skeleton here to act as a base for me to further push the apt content 😅 

I have kept the PR as a draft and will make it open for review once I am done with it.

**Comment by trallard** [comment]
what is the status of this? @HarshCasper @magsol

**Comment by magsol** [comment]
> what is the status of this? @HarshCasper @magsol

Ah! I somehow missed Harsh's most recent changes. I'll review as soon as I can. Thanks @HarshCasper !

**Comment by magsol** [comment]
@HarshCasper I fixed some spelling errors that GitHub flagged, but I'm still seeing link 404s in the Actions. Visual inspection says that these links are fine, but I wanted to check with you before merging.

**Comment by HarshCasper** [comment]
> @HarshCasper I fixed some spelling errors that GitHub flagged, but I'm still seeing link 404s in the Actions. Visual inspection says that these links are fine, but I wanted to check with you before merging.

I have fixed all of them. Thanks for fixing the Vale errors :)

**Comment by magsol** [comment]
Looks like there are some Vale errors in other docs but those can be fixed in a separate PR. I'll go ahead and merge this as soon as I can.

**Review by magsol — APPROVED** [review]
Vale errors were fixed, looks good to merge.

**Pull request merged**
