### PR TITLE
update terraform version to 1.0.0

### LINKED ISSUE #643: Upgrade terraform version to 1.0.0
Terraform is version 1.0.0! Upgrade qhub to depend on this version

### PR DESCRIPTION
**Pull request by utabe**
Closes #643

### CODE REVIEW

**Comment by danlester** [comment]
Thanks for this. I'm trying it out to deploy a fresh deployment through Terraform 1.0.

Have you been able to try out an upgrade successfully? i.e. updating a qhub that was originally deployed through an older Terraform.

**Comment by utabe** [comment]
> Have you been able to try out an upgrade successfully? i.e. updating a qhub that was originally deployed through an older Terraform.
@danlester I have not yet been successful in updating a older deploy.

**Comment by danlester** [comment]
@utabe Thanks for the update. I do think we at least need to be able to give people instructions on how to upgrade. If not possible at all for some reason, we need to think about how to handle this.

**Comment by danlester** [comment]
Closes #643

**Pull request merged**
