### PR TITLE
Delete existing `.gitlab-ci.yml` when rendering 

### PR DESCRIPTION
**Pull request by iameskild**
Issue detected by @viniciusdc when working with a client that uses GitLab. 

To do:
- [ ] Add test for gitlab deployments

### CODE REVIEW

**Comment by viniciusdc** [comment]
@iameskild which kind of test are you expecting?

**Comment by iameskild** [comment]
@viniciusdc sorry I should've specified that I want to add a test for gitlab deployments (initial comment updated). In my PR #874, I made some changes to the test suite that I think will make it easier for us to add tests. I haven't done so yet, but I will make sure that we also test gitlab deployments as part of that PR.

**Comment by viniciusdc** [comment]
> @viniciusdc sorry I should've specified that I want to add a test for gitlab deployments (initial comment updated). In my PR #874, I made some changes to the test suite that I think will make it easier for us to add tests. I haven't done so yet, but I will make sure that we also test gitlab deployments as part of that PR.

Could we add the tests within that PR then? I would like to merge this ASAP if possible

**Comment by iameskild** [comment]
@viniciusdc, feel free to merge this whenever you'd like. I will add some gitlab tests to other PR by the end of the week.

**Review by viniciusdc — APPROVED** [review]
LGTM!

**Pull request merged**
