### PR TITLE
Move ipython config within jupyterlab to docker image with more robust jupyterlab ssh tests

### LINKED ISSUE #1157: [ENH] - Cleanup terminal prompt
### Feature description

When opening a terminal in JupyterLab the prompt could do with some cleanup.

`dharhas@quansight.com@jupyter-dharhas-40quansight-2ecom:~$`

Does `jupyter-dharhas-40quansight-2ecom` have any significance. If not we should just use 

`dharhas@quansight.com:~$` as the prompt

Also, why is `/opt/conda/condabin/conda` be printed twice

We should also consider other things for a nice terminal prompt, i.e. git-prompt integration
 
image

### Value and/or benefit

A clean prompt greatly enhances the usability of the terminal. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by costrouc**
Closes #1157

This PR serves a few purposes. All with the goal of making the docker images simpler (only has installed packages not configuration).
  - reinstating the /etc/skel work that Dan added earlier to jupyterhub/qhub
  - having the jupyter/ipython configuration managed by qhub (ties into the work that vini did in https://github.com/Quansight/qhub/pull/1133)
 - removing the /etc/profile magic from the docker image which lead to weird ssh behavior with jupyterhub_ssh. This will fix the jupyterhub_ssh test and allow us to test the terminal behavior and user environment better.

### CODE REVIEW

**Comment by costrouc** [comment]
Need to test on a local cluster

**Comment by costrouc** [comment]
I've made the jupyterhub_ssh tests quite strict to ensure that the user environment it setup properly. Make take a few tries to get all the tests passing. I also changed the test username to be a complex example to test how jupyterlab handles this `example-user+new1@example.com`.

**Comment by viniciusdc** [comment]
Hi @costrouc I will add this to v0.4.x milestone, is it okay for you?

**Comment by costrouc** [comment]
This PR passes on the cloud tests as well https://github.com/Quansight/qhub-integration-test/runs/5452337353?check_suite_focus=true

**Comment by costrouc** [comment]
@viniciusdc this would be ready for review now that 0.4 has been released

**Comment by viniciusdc** [comment]
> @viniciusdc this would be ready for review now that 0.4 has been released

I will review it thanks @costrouc, as I will deploy it to test the PS1 features and check the configmaps directly, I should finish it by next Monday.

**Review by viniciusdc — APPROVED** [review]
LGTM! I was able to check all configmaps were present and working. The skel configs were pro[agated and I was able to validate the protests.

**Comment by costrouc** [comment]
I updated to the latest in main and if that passes I will merge.

**Pull request merged**
