### PR TITLE
Qhub init

### PR DESCRIPTION
**Pull request by prasunanand**
Fixes https://github.com/Quansight/qhub/issues/73

### CODE REVIEW

**Comment by costrouc** [comment]
Having the config files in templates will cause them to be rendered into the cookiecutter template. Could you move the config files outside of the templates folder. I think you will have to change MANIFEST.in to include those yaml files.

**Comment by costrouc** [comment]
Also please add documentation on the new command into the docs

**Comment by prasunanand** [comment]
@costrouc  Only this directory is rendered https://github.com/Quansight/qhub/tree/master/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D

**Comment by prasunanand** [comment]
```
prasun@prasun-xps:~/dev/new$ qhub render -c qhub-ops-config.yaml -o ./ --force
prasun@prasun-xps:~/dev/new$ tree | grep qhub-ops-config
├── qhub-ops-config.yaml
```

**Comment by prasunanand** [comment]
I put these files in `templates` directory because it sounds like we are following the `template` pattern.

**Comment by costrouc** [comment]
Thanks for the docs and awesome glad we can keep it in the templates directory. Could you also add a test to render do, aws, and gcp?

**Review by costrouc — APPROVED** [review]

**Pull request merged**
