### PR TITLE
use pyproject.toml and setup.cfg for packaging

### PR DESCRIPTION
**Pull request by tonyfast**
## Changes:

- use the modern pep517 convention for building packages
- add setuptools scm as the versioning system

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build related changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by tonyfast** [comment]
turns out flake8 doesn't support pyproject yet

**Comment by tonyfast** [comment]
this fix adds setuptools-scm as a very management system, i've updated the ci scripts for releasing. a release is defined based on the version number of the github release.

setuptools scm infers the next version number from the nearest commit tag.

https://github.com/pypa/setuptools_scm/

**Comment by magsol** [comment]
Looks like your prediction @costrouc about potential conflicts with version was correct.

We should work on this after the 0.4 release.

**Review by magsol — APPROVED** [review]
LGTM.

We just need to make sure moving forward that we're correctly storing version information in the repo branch/tags, and that this information is correctly propagated to the package metadata on builds.

**Pull request merged**
