### PR TITLE
[WIP] Adding notebook tests to QHub Cluster

### PR DESCRIPTION
**Pull request by costrouc**

### CODE REVIEW

**Comment by costrouc** [comment]
This is a PR that will have to wait. Some reason user servers are not launching (possibly because we are not waiting long enough) and additionally user_options are not handled properly in the jupyterhub api server creation due to how the user launcher that qhub creates is designed.

**Comment by danlester** [comment]
Please see my work to run jhubclient from within Cypress if you provide the path to a Python env.

https://github.com/Quansight/qhub/pull/699

**Comment by tonyfast** [comment]
we've marked this as Stale. if y'all want to continue working on this respond before 11/22.

**Comment by tylerpotts** [comment]
per @tonyfast 's comment, closing this out due to being stale. Please re-open if necessary.

**Pull request closed without merging**
