### PR TITLE
Allow jupyterhub.overrides in qhub-config.yaml

### LINKED ISSUE #814: Make zero to jupyterhub configuration overidable
## Description

Related to issue https://github.com/Quansight/qhub/issues/476. Right now it is not possible to easily customize the zero to jupyterhub helm chart with QHub. It would be nice to expose the helm overrides in the `qhub-config.yaml`. This issue will follow very similarly to https://github.com/Quansight/qhub/pull/813.

## Steps

 - the qhub module exposes `jupyterhub-overrides` via https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/meta/qhub/variables.tf#L86. 
 - need to add a `{{ jupyterhub.overrides | jsonify }}` to https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/kubernetes.tf#L203. 
 - add jupyterhub.overrides key to qhub-config.yaml 
 - must be specificed in schema.py https://github.com/Quansight/qhub/blob/main/qhub/schema.py

### PR DESCRIPTION
**Pull request by danlester**
## Changes:

Closes #814 

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [ ] Yes
- [x] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by viniciusdc — COMMENTED** [review]
LGTM, I will test this and see how that goes, thanks @danlester

**Review by costrouc — CHANGES_REQUESTED** [review]
This is a great addition. @danlester could you add this to the docs?

**Comment by danlester** [comment]
Added docs if you are happy to check @viniciusdc ?

**Comment by danlester** [comment]
The latest Helm charts (0.10.0 onwards, including 1.2.0) have a strict networkPolicy as default. This prevented access from hub to Keycloak, and also from singleuser pods to Dask etc.

It only appeared to affect Digital Ocean, not Google Cloud. This may be due to a different network system being in use.

I have disabled the networkPolicy in hub and singleuser now.

**Comment by danlester** [comment]
Also closes #926

**Pull request merged**
