### PR TITLE
Update theme welcome messages to use Nebari

### LINKED ISSUE #1390: [ENH] - Update theme Welcome message
### Feature description

The current Welcome message is outdated and sends the user to an invalid repository.

- Update the `theme.jupyterhub.welcome` to a proper welcoming message. [ref.](https://github.com/Quansight/qhub/blob/ee41b5eb41632b23adc6b1d1a62e67abd6937bac/qhub/initialize.py#L327)

### Value and/or benefit

User-friendly and proper/useful information

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pavithraes**
Fixes | Closes | Resolves #1390

## Changes introduced in this PR:

- Updated messaging for Nebari

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by trallard — APPROVED** [review]
LGTM - only note is if we intentionally dropped the `{qhub_domain}` well nebari on purpose?

**Comment by trallard** [comment]
Also do we need to change the target branch to `release/2022.10.1`?

**Comment by pavithraes** [comment]
>  only note is if we intentionally dropped the {qhub_domain} well nebari on purpose?

I did drop that on purpose. I figured since users have already navigated to the domain, we don't provide new information by displaying it, but let me know if we want to add it back!

**Comment by pavithraes** [comment]
Huh, that's weird.

**Comment by pavithraes** [comment]
Oops, I didn't even realize it. I'll open a new PR.

**Pull request closed without merging**
